services:
  - type: web
    name: signals-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python crypto_signals_bot/src/main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false


